projects:
  james-one:
    path: /var/www/james-one
    update_url: /opt/ai-updater/updates/james-one/latest.zip
    service: james-one.service

  ai-updater:
    path: /opt/ai-updater
    update_url: /opt/ai-updater/updates/ai-updater/latest.zip
    service: ai-updater.service

  ai-team:
    path: /var/www/ai-team
    update_url: /opt/ai-updater/updates/ai-team/latest.zip
    service: ea.service      # Hauptdienst im Team; kannst später mehrere Services angeben
